### ISSUE TITLE
Where is the correct location on my downloaded yolo-model?

### ISSUE THREAD

**Issue by bemoregt** [shadowcz007/comfyui-ultralytics-yolo#1]
Hi, @shadowcz007 

Where is the correct location on my downloaded yolo-model?

I cannot load the model in Detect label node.

Thanks in advance.

Best,
@bemoregt.

**Comment by shadowcz007** [comment]
ComfyUI\models\ultralytics

ultralytics/[assets](https://github.com/ultralytics/assets/releases/)

[yolo-world](https://docs.ultralytics.com/zh/models/yolo-world/#available-models-supported-tasks-and-operating-modes)
